FileAST(
    ext=[
        FuncDef(
            decl=Decl(
                name='main',
                quals=[],
                align=[],
                storage=[],
                funcspec=[],
                type=FuncDecl(
                    args=None,
                    type=TypeDecl(
                        declname='main',
                        quals=[],
                        align=None,
                        type=IdentifierType(
                            names=['int']
                        )
                    )
                ),
                init=None,
                bitsize=None
            ),
            param_decls=None,
            body=Compound(
                block_items=[
                    Assignment(
                        op='=',
                        lvalue=ID(name='k'),
                        rvalue=ID(name='p')
                    ),
                    FuncCall(
                        name=ID(
                            name='printf'
                        ),
                        args=ExprList(
                            exprs=[
                                Constant(
                                    type='string',
                                    value='"%d"'
                                ),
                                ID(name='b')
                            ]
                        )
                    ),
                    Return(
                        expr=Constant(
                            type='int',
                            value='0'
                        )
                    )
                ]
            )
        )
    ]
)